sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t samcamcode/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true samcamcode/docker-react npm run test